import type { Metadata } from "next";
import { Inter, Recursive } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const recursive = Recursive({subsets: ['latin']})

export const metadata: Metadata = {
  title: "caseCobra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={recursive.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
      
    </html>
  );
}
